name: Manually triggered build and push

on:
  workflow_dispatch:
    inputs:
      code-server-release:
        description: 'Code Server Release'
        required: true

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v3

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKERHUB_REPOSITORY }}
          labels: |
            org.opencontainers.image.description='VS Code in the browser'
            org.opencontainers.image.version=${{ github.event.inputs.code-server-release }}

      -
        name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_REPOSITORY }}:${{ github.event.inputs.code-server-release }}
            ${{ secrets.DOCKERHUB_REPOSITORY }}:latest
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            CODE_RELEASE=${{ github.event.inputs.code-server-release }}
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
